### ISSUE TITLE
AttributeError when login form does not validate.

### ISSUE THREAD

**Issue by erikberglund** [nickw444/flask-ldap3-login#76]
I get the following error when a user tries to log in with invalid credentials:

```
ERROR:flask.app:Exception on /api/auth/login [POST]
Traceback (most recent call last):
    File "/var/www/site/backend/auth/api.py", line 42, in post
        if form.validate_ldap():
    File "/var/www/site/venv/lib/python3.6/site-packages/flask_ldap3_login/forms.py", line 51, in validate_ldap
        self.username.errors.append('Invalid Username/Password.')
AttributeError: 'tuple' object has no attribute 'append'
```

So something might have changed in a WTForms update to make the errors object a tuple?

I'm using:
- Python 3.6
- flask-ldap3-login 0.9.16
- WTForms 2.2.1

**Comment by gmacon** [comment]
That seems like a reasonable hypothesis. Next action here is probably to investigate the Flask-WTF and WTForms change logs to identify an appropriate minimum version.

**Comment by YuKaiTe** [comment]
Hi! I had the same issue and found a solution that worked for me, instead of validate_ldap() use validate().
